---
- hosts: tag_Name_Node
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2
    apt:
      name: "{{ mywebpack }}"
      state: present

  - name: apache service restart
    service:
      name: "{{ mywebpack }}"
      state: started
  - name: debug
    debug:
      msg: "{{ ansible_os_family }}"
