---
- hosts: tag_Name_Node
  become: yes
  gather_facts: no 
  tasks:
  - name: install apache2
    apt:
      name: "{{ mywebpack }}"
      state: present

  - name: apache service restart
    service:
     state: start

