---
- hosts:  18.219.229.32 , 3.145.29.170
  become: yes
  gather_facts: yes
  tasks:
  - name: install apache2
    apt:
      name: "{{ mywebpack }}"
      state: present
    tags: httpd

  - name: apache service restart
    service:
      name: "{{ mywebpack }}"
      state: started
    tags: start

  - name: debug
    debug:
      msg: "{{ ansible_os_family }}"
    register: platform

  - name: debug
    debug:
      msg: "{{ platform }}"
  