---
- hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
  - name: create nodes
    ec2:
      key_name: key
      image: ami-05803413c51f242b7
      instance_type: t2.micro
      count: 3
      wait: yes
      group: launch-wizard-1
      region: us-east-2
      vpc_subnet_id: subnet-0f3017669dbf55902
      assign_public_ip: yes
      instance_tags:
         Name: Ubuntu
