---
- hosts: tag_Name_Ubuntu
  become: yes
  tasks:
  - name: update cache
    apt:
     update_cache: yes

  - name: Install mysql-server
    apt:
     name: mysql-server
     state: present

  - name: 
    command: mysql_secure_installation