---
- name: file path
  file:
    path: /opt/tomcat
    group: tomcat
    recurse: yes
    state: directory

- name: tomcat group read access
  file: 
   path: /opt/tomcat/conf
   group: tomcat
   mode : g+r
   recurse: yes
   state: directory

- name: tomcat group execute access
  file: 
   path: /opt/tomcat/conf
   group: tomcat
   mode : g+x
   state: directory


- name: tomcat user the owner of the webapps
  file: 
   path: /opt/tomcat/webapps
   owner: tomcat
   recurse: yes
   state: directory

- name: tomcat user the owner of the work
  file: 
   path: /opt/tomcat/work
   owner: tomcat
   recurse: yes
   state: directory

- name: tomcat user the owner of the temp
  file: 
   path: /opt/tomcat/temp
   owner: tomcat
   recurse: yes
   state: directory

- name: tomcat user the owner of the logs
  file: 
   path: /opt/tomcat/logs
   owner: tomcat
   recurse: yes
   state: directory