--- 
- name: tomcat service
  template:
     src: templates/tomcatservice.j2
     dest: /etc/systemd/system/tomcat.service

- name: tomcat restart
  systemd: 
   daemon-reload: yes
   state: restarted
   enabled: yes
   name: tomcat