---
- name: tomcat user details
  template: 
    src: templates/tomcat-user.j2
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: tomcat manager context details
  template: 
    src: templates/manager.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: tomcat hostmanager context details
  template: 
    src: templates/hostmana ger.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml

- name: system restarted
  systemd:
     state: restarted
     name: tomcat